SOURCES=$(notdir $(shell find . -iname '*.c'))
HEADERS=$(notdir $(shell find . -iname '*.h'))
OBJS=$(SOURCES:.c=.o)
BUILDDIR=../../../results/testLibrary

all: $(BUILDDIR)/testLibrary.dylib

$(BUILDDIR)/testLibrary.dylib: $(BUILDDIR) $(addprefix $(BUILDDIR)/,$(OBJS))
	clang -dynamiclib -arch i386 -arch x86_64 $(BUILDDIR)/*.o -o $(BUILDDIR)/testLibrary.dylib

$(BUILDDIR): 
	mkdir -p $(BUILDDIR)

$(BUILDDIR)/%.o: %.c $(HEADERS)
	clang -arch i386 -arch x86_64 -c $< -o $@

clean: 
	rm -rf $(BUILDDIR)
	
